### ISSUE TITLE
BUG() triggered by removing a (loopback block) device

### ISSUE THREAD

**Issue by klihub** [MatiasBjorling/kvblade#4]
While testing on kernel 5.10.19-200.fc33.x86_64 (stock fedora 32),
removing an idle device (umounted and flushed on client) triggers a kernel
scheduling while atomic BUG(). Related dmesg parts attached.

[bug-on-removal.log](https://github.com/MatiasBjorling/kvblade/files/6097684/bug-on-removal.log)

**Comment by klihub** [comment]
Actually, this only seems to happen if the deleted device is a loopback device.

**Comment by klihub** [comment]
And #5 is a proposed fix for this problem.

**Comment by MatiasBjorling** [comment]
Thanks!
